### ISSUE TITLE
[Question] ParseError : inherit setuptools pypi distutils native

### ISSUE THREAD

**Issue by soimsoim** [dl9pf/meta-spdxscanner#18]
When I try to build meta-spdxscanner in pocky, I get the following error: How could I solve it?

ERROR: ParseError at /pocky_spdx/poky/meta-spdxscanner/recipes-devtools/scancode-toolkit/scancode-toolkit-native_3.1.1.bb:13: Could not inherit file classes/setuptools.bbclass
(inherit setuptools pypi distutils native)

Is there a pokcy version suitable for testing?

Thanks & Regards,
Soim

**Comment by soimsoim** [comment]
When I try to build git://git.openembedded.org/openembedded-core by adding meta-spdxscanner, it doesn't show ParseError that I mentioned.

I tried to scancode anlysis  by adding below to conf/local.conf.
> INHERIT += "scancode-tk"

But it shows below error message.
> Aborted dependency loops search after 10 matches.

**Comment by soimsoim** [comment]
The following description was found. How do I use meta-spdxscanner/classes/nopackages.bbclass instead the file comes from oe-core?
> To aviod loop dependence,please use meta-spdxscanner/classes/nopackages.bbclass instead the file comes from oe-core.

Now we're building with ihherit += scancode-tk, nopackages as well. 
The build seems to be successful.

**Comment by leimaohui** [comment]
That’s great! Please contact me when you have any question.

**Comment by soimsoim** [comment]
The following description was found. How do I use meta-spdxscanner/classes/nopackages.bbclass instead the file comes from oe-core?

I tried to build with ihherit + = scancode-tk, nopackages, but I failed.

**Comment by leimaohui** [comment]
> The following description was found. How do I use meta-spdxscanner/classes/nopackages.bbclass instead the file comes from oe-core?

Please modified nopackages.bbclass of oe-core manually or cover it by meta-spdxscanner/classes/nopackages.bbclass. Later I'll try to submit this patch into poky community again.

**Comment by soimsoim** [comment]
I modified it as you commented and it is analyzed for every package in the whole build!
Thank you so much.
